package com.ykt.backstage.dao;

import com.ykt.backstage.entity.CardAccounts;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface CardAccountsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_accounts
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String cardNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_accounts
     *
     * @mbg.generated
     */
    int insert(CardAccounts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_accounts
     *
     * @mbg.generated
     */
    CardAccounts selectByPrimaryKey(String cardNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_accounts
     *
     * @mbg.generated
     */
    List<CardAccounts> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_accounts
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CardAccounts record);
}