package com.ykt.backstage.dao;

import com.ykt.backstage.entity.DoorInfos;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface DoorInfosMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table door_infos
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table door_infos
     *
     * @mbg.generated
     */
    int insert(DoorInfos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table door_infos
     *
     * @mbg.generated
     */
    DoorInfos selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table door_infos
     *
     * @mbg.generated
     */
    List<DoorInfos> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table door_infos
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DoorInfos record);
}