package com.ykt.backstage.dao;

import com.ykt.backstage.entity.Dormitory;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface DormitoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String xh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory
     *
     * @mbg.generated
     */
    int insert(Dormitory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory
     *
     * @mbg.generated
     */
    Dormitory selectByPrimaryKey(String xh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory
     *
     * @mbg.generated
     */
    List<Dormitory> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Dormitory record);
}