package com.ykt.backstage.dao;

import com.ykt.backstage.entity.SchoolCalendarDetails;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface SchoolCalendarDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_calendar_details
     *
     * @mbg.generated
     */
    int insert(SchoolCalendarDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_calendar_details
     *
     * @mbg.generated
     */
    List<SchoolCalendarDetails> selectAll();
}