package com.ykt.backstage.dao;

import com.ykt.backstage.entity.TeacherClasses;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface TeacherClassesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_classes
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_classes
     *
     * @mbg.generated
     */
    int insert(TeacherClasses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_classes
     *
     * @mbg.generated
     */
    TeacherClasses selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_classes
     *
     * @mbg.generated
     */
    List<TeacherClasses> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_classes
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TeacherClasses record);
}