server:
  port: 8080
  tomcat:
    max-http-form-post-size: 20MB

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/onecard?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 5s
    lettuce:
      pool:
        min-idle: 2
        max-active: 8
        max-idle: 4

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    aggressive-lazy-loading: false
    lazy-loading-enabled: true
    jdbc-type-for-null: null
    cache-enabled: true

