package com.ykt.backstage.entity;

import java.io.Serializable;
import java.util.Date;

public class ApplyRecords implements Serializable {

    private Integer id;
    private String sno;

    private String card;
    private String siteId;

    private Date applyTime;
    private String administratorId;
    private Date handleTime;
    private String handleStatus;
    private String description;

    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getSno() {
        return sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_records.sno
     *
     * @param sno the value for apply_records.sno
     * @mbg.generated
     */
    public void setSno(String sno) {
        this.sno = sno == null ? null : sno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_records.card
     *
     * @return the value of apply_records.card
     * @mbg.generated
     */
    public String getCard() {
        return card;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_records.card
     *
     * @param card the value for apply_records.card
     * @mbg.generated
     */
    public void setCard(String card) {
        this.card = card == null ? null : card.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_records.site_id
     *
     * @return the value of apply_records.site_id
     * @mbg.generated
     */
    public String getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_records.site_id
     *
     * @param siteId the value for apply_records.site_id
     * @mbg.generated
     */
    public void setSiteId(String siteId) {
        this.siteId = siteId == null ? null : siteId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_records.apply_time
     *
     * @return the value of apply_records.apply_time
     * @mbg.generated
     */
    public Date getApplyTime() {
        return applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_records.apply_time
     *
     * @param applyTime the value for apply_records.apply_time
     * @mbg.generated
     */
    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_records.administrator_id
     *
     * @return the value of apply_records.administrator_id
     * @mbg.generated
     */
    public String getAdministratorId() {
        return administratorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_records.administrator_id
     *
     * @param administratorId the value for apply_records.administrator_id
     * @mbg.generated
     */
    public void setAdministratorId(String administratorId) {
        this.administratorId = administratorId == null ? null : administratorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_records.handle_time
     *
     * @return the value of apply_records.handle_time
     * @mbg.generated
     */
    public Date getHandleTime() {
        return handleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_records.handle_time
     *
     * @param handleTime the value for apply_records.handle_time
     * @mbg.generated
     */
    public void setHandleTime(Date handleTime) {
        this.handleTime = handleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_records.handle_status
     *
     * @return the value of apply_records.handle_status
     * @mbg.generated
     */
    public String getHandleStatus() {
        return handleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_records.handle_status
     *
     * @param handleStatus the value for apply_records.handle_status
     * @mbg.generated
     */
    public void setHandleStatus(String handleStatus) {
        this.handleStatus = handleStatus == null ? null : handleStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_records.description
     *
     * @return the value of apply_records.description
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_records.description
     *
     * @param description the value for apply_records.description
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_records
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", sno=").append(sno);
        sb.append(", card=").append(card);
        sb.append(", siteId=").append(siteId);
        sb.append(", applyTime=").append(applyTime);
        sb.append(", administratorId=").append(administratorId);
        sb.append(", handleTime=").append(handleTime);
        sb.append(", handleStatus=").append(handleStatus);
        sb.append(", description=").append(description);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}