package com.ykt.backstage.entity;

import java.io.Serializable;
import java.util.Date;

public class BookLibraryInfos implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_library_infos.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_library_infos.book_code
     *
     * @mbg.generated
     */
    private String bookCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_library_infos.book_name
     *
     * @mbg.generated
     */
    private String bookName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_library_infos.person_type
     *
     * @mbg.generated
     */
    private Integer personType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_library_infos.person_name
     *
     * @mbg.generated
     */
    private String personName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_library_infos.department_name
     *
     * @mbg.generated
     */
    private String departmentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_library_infos.department_code
     *
     * @mbg.generated
     */
    private String departmentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_library_infos.person_no
     *
     * @mbg.generated
     */
    private String personNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_library_infos.borrowed_time
     *
     * @mbg.generated
     */
    private String borrowedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_library_infos.returned_time
     *
     * @mbg.generated
     */
    private String returnedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_library_infos.is_refill
     *
     * @mbg.generated
     */
    private Integer isRefill;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_library_infos.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_library_infos.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_library_infos.should_return_time
     *
     * @mbg.generated
     */
    private String shouldReturnTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_library_infos.operate_type
     *
     * @mbg.generated
     */
    private String operateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_library_infos.payment_amount
     *
     * @mbg.generated
     */
    private String paymentAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table book_library_infos
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_library_infos.id
     *
     * @return the value of book_library_infos.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_library_infos.id
     *
     * @param id the value for book_library_infos.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_library_infos.book_code
     *
     * @return the value of book_library_infos.book_code
     * @mbg.generated
     */
    public String getBookCode() {
        return bookCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_library_infos.book_code
     *
     * @param bookCode the value for book_library_infos.book_code
     * @mbg.generated
     */
    public void setBookCode(String bookCode) {
        this.bookCode = bookCode == null ? null : bookCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_library_infos.book_name
     *
     * @return the value of book_library_infos.book_name
     * @mbg.generated
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_library_infos.book_name
     *
     * @param bookName the value for book_library_infos.book_name
     * @mbg.generated
     */
    public void setBookName(String bookName) {
        this.bookName = bookName == null ? null : bookName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_library_infos.person_type
     *
     * @return the value of book_library_infos.person_type
     * @mbg.generated
     */
    public Integer getPersonType() {
        return personType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_library_infos.person_type
     *
     * @param personType the value for book_library_infos.person_type
     * @mbg.generated
     */
    public void setPersonType(Integer personType) {
        this.personType = personType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_library_infos.person_name
     *
     * @return the value of book_library_infos.person_name
     * @mbg.generated
     */
    public String getPersonName() {
        return personName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_library_infos.person_name
     *
     * @param personName the value for book_library_infos.person_name
     * @mbg.generated
     */
    public void setPersonName(String personName) {
        this.personName = personName == null ? null : personName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_library_infos.department_name
     *
     * @return the value of book_library_infos.department_name
     * @mbg.generated
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_library_infos.department_name
     *
     * @param departmentName the value for book_library_infos.department_name
     * @mbg.generated
     */
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName == null ? null : departmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_library_infos.department_code
     *
     * @return the value of book_library_infos.department_code
     * @mbg.generated
     */
    public String getDepartmentCode() {
        return departmentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_library_infos.department_code
     *
     * @param departmentCode the value for book_library_infos.department_code
     * @mbg.generated
     */
    public void setDepartmentCode(String departmentCode) {
        this.departmentCode = departmentCode == null ? null : departmentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_library_infos.person_no
     *
     * @return the value of book_library_infos.person_no
     * @mbg.generated
     */
    public String getPersonNo() {
        return personNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_library_infos.person_no
     *
     * @param personNo the value for book_library_infos.person_no
     * @mbg.generated
     */
    public void setPersonNo(String personNo) {
        this.personNo = personNo == null ? null : personNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_library_infos.borrowed_time
     *
     * @return the value of book_library_infos.borrowed_time
     * @mbg.generated
     */
    public String getBorrowedTime() {
        return borrowedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_library_infos.borrowed_time
     *
     * @param borrowedTime the value for book_library_infos.borrowed_time
     * @mbg.generated
     */
    public void setBorrowedTime(String borrowedTime) {
        this.borrowedTime = borrowedTime == null ? null : borrowedTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_library_infos.returned_time
     *
     * @return the value of book_library_infos.returned_time
     * @mbg.generated
     */
    public String getReturnedTime() {
        return returnedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_library_infos.returned_time
     *
     * @param returnedTime the value for book_library_infos.returned_time
     * @mbg.generated
     */
    public void setReturnedTime(String returnedTime) {
        this.returnedTime = returnedTime == null ? null : returnedTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_library_infos.is_refill
     *
     * @return the value of book_library_infos.is_refill
     * @mbg.generated
     */
    public Integer getIsRefill() {
        return isRefill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_library_infos.is_refill
     *
     * @param isRefill the value for book_library_infos.is_refill
     * @mbg.generated
     */
    public void setIsRefill(Integer isRefill) {
        this.isRefill = isRefill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_library_infos.created_at
     *
     * @return the value of book_library_infos.created_at
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_library_infos.created_at
     *
     * @param createdAt the value for book_library_infos.created_at
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_library_infos.updated_at
     *
     * @return the value of book_library_infos.updated_at
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_library_infos.updated_at
     *
     * @param updatedAt the value for book_library_infos.updated_at
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_library_infos.should_return_time
     *
     * @return the value of book_library_infos.should_return_time
     * @mbg.generated
     */
    public String getShouldReturnTime() {
        return shouldReturnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_library_infos.should_return_time
     *
     * @param shouldReturnTime the value for book_library_infos.should_return_time
     * @mbg.generated
     */
    public void setShouldReturnTime(String shouldReturnTime) {
        this.shouldReturnTime = shouldReturnTime == null ? null : shouldReturnTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_library_infos.operate_type
     *
     * @return the value of book_library_infos.operate_type
     * @mbg.generated
     */
    public String getOperateType() {
        return operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_library_infos.operate_type
     *
     * @param operateType the value for book_library_infos.operate_type
     * @mbg.generated
     */
    public void setOperateType(String operateType) {
        this.operateType = operateType == null ? null : operateType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_library_infos.payment_amount
     *
     * @return the value of book_library_infos.payment_amount
     * @mbg.generated
     */
    public String getPaymentAmount() {
        return paymentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_library_infos.payment_amount
     *
     * @param paymentAmount the value for book_library_infos.payment_amount
     * @mbg.generated
     */
    public void setPaymentAmount(String paymentAmount) {
        this.paymentAmount = paymentAmount == null ? null : paymentAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_library_infos
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", bookCode=").append(bookCode);
        sb.append(", bookName=").append(bookName);
        sb.append(", personType=").append(personType);
        sb.append(", personName=").append(personName);
        sb.append(", departmentName=").append(departmentName);
        sb.append(", departmentCode=").append(departmentCode);
        sb.append(", personNo=").append(personNo);
        sb.append(", borrowedTime=").append(borrowedTime);
        sb.append(", returnedTime=").append(returnedTime);
        sb.append(", isRefill=").append(isRefill);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append(", shouldReturnTime=").append(shouldReturnTime);
        sb.append(", operateType=").append(operateType);
        sb.append(", paymentAmount=").append(paymentAmount);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}