package com.ykt.backstage.entity;

import java.io.Serializable;
import java.util.Date;

public class CardTransactions implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_transactions.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_transactions.transaction_id
     *
     * @mbg.generated
     */
    private Long transactionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_transactions.transaction_date
     *
     * @mbg.generated
     */
    private String transactionDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_transactions.transaction_time
     *
     * @mbg.generated
     */
    private Date transactionTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_transactions.transaction_amount
     *
     * @mbg.generated
     */
    private Integer transactionAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_transactions.transaction_type
     *
     * @mbg.generated
     */
    private String transactionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_transactions.transaction_status
     *
     * @mbg.generated
     */
    private Integer transactionStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_transactions.merchant_code
     *
     * @mbg.generated
     */
    private String merchantCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_transactions.sno
     *
     * @mbg.generated
     */
    private String sno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_transactions.card_account_num
     *
     * @mbg.generated
     */
    private String cardAccountNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_transactions.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table card_transactions
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_transactions.id
     *
     * @return the value of card_transactions.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_transactions.id
     *
     * @param id the value for card_transactions.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_transactions.transaction_id
     *
     * @return the value of card_transactions.transaction_id
     * @mbg.generated
     */
    public Long getTransactionId() {
        return transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_transactions.transaction_id
     *
     * @param transactionId the value for card_transactions.transaction_id
     * @mbg.generated
     */
    public void setTransactionId(Long transactionId) {
        this.transactionId = transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_transactions.transaction_date
     *
     * @return the value of card_transactions.transaction_date
     * @mbg.generated
     */
    public String getTransactionDate() {
        return transactionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_transactions.transaction_date
     *
     * @param transactionDate the value for card_transactions.transaction_date
     * @mbg.generated
     */
    public void setTransactionDate(String transactionDate) {
        this.transactionDate = transactionDate == null ? null : transactionDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_transactions.transaction_time
     *
     * @return the value of card_transactions.transaction_time
     * @mbg.generated
     */
    public Date getTransactionTime() {
        return transactionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_transactions.transaction_time
     *
     * @param transactionTime the value for card_transactions.transaction_time
     * @mbg.generated
     */
    public void setTransactionTime(Date transactionTime) {
        this.transactionTime = transactionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_transactions.transaction_amount
     *
     * @return the value of card_transactions.transaction_amount
     * @mbg.generated
     */
    public Integer getTransactionAmount() {
        return transactionAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_transactions.transaction_amount
     *
     * @param transactionAmount the value for card_transactions.transaction_amount
     * @mbg.generated
     */
    public void setTransactionAmount(Integer transactionAmount) {
        this.transactionAmount = transactionAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_transactions.transaction_type
     *
     * @return the value of card_transactions.transaction_type
     * @mbg.generated
     */
    public String getTransactionType() {
        return transactionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_transactions.transaction_type
     *
     * @param transactionType the value for card_transactions.transaction_type
     * @mbg.generated
     */
    public void setTransactionType(String transactionType) {
        this.transactionType = transactionType == null ? null : transactionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_transactions.transaction_status
     *
     * @return the value of card_transactions.transaction_status
     * @mbg.generated
     */
    public Integer getTransactionStatus() {
        return transactionStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_transactions.transaction_status
     *
     * @param transactionStatus the value for card_transactions.transaction_status
     * @mbg.generated
     */
    public void setTransactionStatus(Integer transactionStatus) {
        this.transactionStatus = transactionStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_transactions.merchant_code
     *
     * @return the value of card_transactions.merchant_code
     * @mbg.generated
     */
    public String getMerchantCode() {
        return merchantCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_transactions.merchant_code
     *
     * @param merchantCode the value for card_transactions.merchant_code
     * @mbg.generated
     */
    public void setMerchantCode(String merchantCode) {
        this.merchantCode = merchantCode == null ? null : merchantCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_transactions.sno
     *
     * @return the value of card_transactions.sno
     * @mbg.generated
     */
    public String getSno() {
        return sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_transactions.sno
     *
     * @param sno the value for card_transactions.sno
     * @mbg.generated
     */
    public void setSno(String sno) {
        this.sno = sno == null ? null : sno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_transactions.card_account_num
     *
     * @return the value of card_transactions.card_account_num
     * @mbg.generated
     */
    public String getCardAccountNum() {
        return cardAccountNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_transactions.card_account_num
     *
     * @param cardAccountNum the value for card_transactions.card_account_num
     * @mbg.generated
     */
    public void setCardAccountNum(String cardAccountNum) {
        this.cardAccountNum = cardAccountNum == null ? null : cardAccountNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_transactions.created_at
     *
     * @return the value of card_transactions.created_at
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_transactions.created_at
     *
     * @param createdAt the value for card_transactions.created_at
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_transactions
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", transactionId=").append(transactionId);
        sb.append(", transactionDate=").append(transactionDate);
        sb.append(", transactionTime=").append(transactionTime);
        sb.append(", transactionAmount=").append(transactionAmount);
        sb.append(", transactionType=").append(transactionType);
        sb.append(", transactionStatus=").append(transactionStatus);
        sb.append(", merchantCode=").append(merchantCode);
        sb.append(", sno=").append(sno);
        sb.append(", cardAccountNum=").append(cardAccountNum);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}