package com.ykt.backstage.entity;

import java.io.Serializable;
import java.util.Date;

public class CardMerchants implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_merchants.merchant_code
     *
     * @mbg.generated
     */
    private String merchantCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_merchants.merchant_name
     *
     * @mbg.generated
     */
    private String merchantName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_merchants.location
     *
     * @mbg.generated
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_merchants.created_at
     *
     * @mbg.generated
     */
    private String createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_merchants.updated_at
     *
     * @mbg.generated
     */
    private String updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_merchants.brand_type
     *
     * @mbg.generated
     */
    private String brandType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_merchants.campus_location
     *
     * @mbg.generated
     */
    private String campusLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table card_merchants
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_merchants.merchant_code
     *
     * @return the value of card_merchants.merchant_code
     * @mbg.generated
     */
    public String getMerchantCode() {
        return merchantCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_merchants.merchant_code
     *
     * @param merchantCode the value for card_merchants.merchant_code
     * @mbg.generated
     */
    public void setMerchantCode(String merchantCode) {
        this.merchantCode = merchantCode == null ? null : merchantCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_merchants.merchant_name
     *
     * @return the value of card_merchants.merchant_name
     * @mbg.generated
     */
    public String getMerchantName() {
        return merchantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_merchants.merchant_name
     *
     * @param merchantName the value for card_merchants.merchant_name
     * @mbg.generated
     */
    public void setMerchantName(String merchantName) {
        this.merchantName = merchantName == null ? null : merchantName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_merchants.location
     *
     * @return the value of card_merchants.location
     * @mbg.generated
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_merchants.location
     *
     * @param location the value for card_merchants.location
     * @mbg.generated
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_merchants.created_at
     *
     * @return the value of card_merchants.created_at
     * @mbg.generated
     */
    public String getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_merchants.created_at
     *
     * @param createdAt the value for card_merchants.created_at
     * @mbg.generated
     */
    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_merchants.updated_at
     *
     * @return the value of card_merchants.updated_at
     * @mbg.generated
     */
    public String getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_merchants.updated_at
     *
     * @param updatedAt the value for card_merchants.updated_at
     * @mbg.generated
     */
    public void setUpdatedAt(String updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_merchants.brand_type
     *
     * @return the value of card_merchants.brand_type
     * @mbg.generated
     */
    public String getBrandType() {
        return brandType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_merchants.brand_type
     *
     * @param brandType the value for card_merchants.brand_type
     * @mbg.generated
     */
    public void setBrandType(String brandType) {
        this.brandType = brandType == null ? null : brandType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_merchants.campus_location
     *
     * @return the value of card_merchants.campus_location
     * @mbg.generated
     */
    public String getCampusLocation() {
        return campusLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_merchants.campus_location
     *
     * @param campusLocation the value for card_merchants.campus_location
     * @mbg.generated
     */
    public void setCampusLocation(String campusLocation) {
        this.campusLocation = campusLocation == null ? null : campusLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_merchants
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", merchantCode=").append(merchantCode);
        sb.append(", merchantName=").append(merchantName);
        sb.append(", location=").append(location);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append(", brandType=").append(brandType);
        sb.append(", campusLocation=").append(campusLocation);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}