package com.ykt.backstage.entity;

import java.io.Serializable;
import java.util.Date;

public class CardAccounts implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_accounts.card_no
     *
     * @mbg.generated
     */
    private String cardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_accounts.sno
     *
     * @mbg.generated
     */
    private String sno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_accounts.regist_date
     *
     * @mbg.generated
     */
    private String registDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_accounts.validity_date
     *
     * @mbg.generated
     */
    private String validityDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_accounts.bank_account
     *
     * @mbg.generated
     */
    private String bankAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_accounts.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_accounts.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_accounts.sub_person_type
     *
     * @mbg.generated
     */
    private String subPersonType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_accounts.balance
     *
     * @mbg.generated
     */
    private String balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_accounts.water
     *
     * @mbg.generated
     */
    private String water;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_accounts.electricity
     *
     * @mbg.generated
     */
    private String electricity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_accounts.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table card_accounts
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_accounts.card_no
     *
     * @return the value of card_accounts.card_no
     * @mbg.generated
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_accounts.card_no
     *
     * @param cardNo the value for card_accounts.card_no
     * @mbg.generated
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_accounts.sno
     *
     * @return the value of card_accounts.sno
     * @mbg.generated
     */
    public String getSno() {
        return sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_accounts.sno
     *
     * @param sno the value for card_accounts.sno
     * @mbg.generated
     */
    public void setSno(String sno) {
        this.sno = sno == null ? null : sno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_accounts.regist_date
     *
     * @return the value of card_accounts.regist_date
     * @mbg.generated
     */
    public String getRegistDate() {
        return registDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_accounts.regist_date
     *
     * @param registDate the value for card_accounts.regist_date
     * @mbg.generated
     */
    public void setRegistDate(String registDate) {
        this.registDate = registDate == null ? null : registDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_accounts.validity_date
     *
     * @return the value of card_accounts.validity_date
     * @mbg.generated
     */
    public String getValidityDate() {
        return validityDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_accounts.validity_date
     *
     * @param validityDate the value for card_accounts.validity_date
     * @mbg.generated
     */
    public void setValidityDate(String validityDate) {
        this.validityDate = validityDate == null ? null : validityDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_accounts.bank_account
     *
     * @return the value of card_accounts.bank_account
     * @mbg.generated
     */
    public String getBankAccount() {
        return bankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_accounts.bank_account
     *
     * @param bankAccount the value for card_accounts.bank_account
     * @mbg.generated
     */
    public void setBankAccount(String bankAccount) {
        this.bankAccount = bankAccount == null ? null : bankAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_accounts.created_at
     *
     * @return the value of card_accounts.created_at
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_accounts.created_at
     *
     * @param createdAt the value for card_accounts.created_at
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_accounts.updated_at
     *
     * @return the value of card_accounts.updated_at
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_accounts.updated_at
     *
     * @param updatedAt the value for card_accounts.updated_at
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_accounts.sub_person_type
     *
     * @return the value of card_accounts.sub_person_type
     * @mbg.generated
     */
    public String getSubPersonType() {
        return subPersonType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_accounts.sub_person_type
     *
     * @param subPersonType the value for card_accounts.sub_person_type
     * @mbg.generated
     */
    public void setSubPersonType(String subPersonType) {
        this.subPersonType = subPersonType == null ? null : subPersonType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_accounts.balance
     *
     * @return the value of card_accounts.balance
     * @mbg.generated
     */
    public String getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_accounts.balance
     *
     * @param balance the value for card_accounts.balance
     * @mbg.generated
     */
    public void setBalance(String balance) {
        this.balance = balance == null ? null : balance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_accounts.water
     *
     * @return the value of card_accounts.water
     * @mbg.generated
     */
    public String getWater() {
        return water;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_accounts.water
     *
     * @param water the value for card_accounts.water
     * @mbg.generated
     */
    public void setWater(String water) {
        this.water = water == null ? null : water.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_accounts.electricity
     *
     * @return the value of card_accounts.electricity
     * @mbg.generated
     */
    public String getElectricity() {
        return electricity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_accounts.electricity
     *
     * @param electricity the value for card_accounts.electricity
     * @mbg.generated
     */
    public void setElectricity(String electricity) {
        this.electricity = electricity == null ? null : electricity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_accounts.status
     *
     * @return the value of card_accounts.status
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_accounts.status
     *
     * @param status the value for card_accounts.status
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_accounts
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", cardNo=").append(cardNo);
        sb.append(", sno=").append(sno);
        sb.append(", registDate=").append(registDate);
        sb.append(", validityDate=").append(validityDate);
        sb.append(", bankAccount=").append(bankAccount);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append(", subPersonType=").append(subPersonType);
        sb.append(", balance=").append(balance);
        sb.append(", water=").append(water);
        sb.append(", electricity=").append(electricity);
        sb.append(", status=").append(status);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}