package com.ykt.backstage.entity;

import java.io.Serializable;
import java.util.Date;

public class DoorInfos implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column door_infos.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column door_infos.sno
     *
     * @mbg.generated
     */
    private String sno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column door_infos.door_name
     *
     * @mbg.generated
     */
    private String doorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column door_infos.building_code
     *
     * @mbg.generated
     */
    private String buildingCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column door_infos.door_type
     *
     * @mbg.generated
     */
    private Integer doorType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column door_infos.door_building
     *
     * @mbg.generated
     */
    private String doorBuilding;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column door_infos.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column door_infos.door_code
     *
     * @mbg.generated
     */
    private String doorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table door_infos
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column door_infos.id
     *
     * @return the value of door_infos.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column door_infos.id
     *
     * @param id the value for door_infos.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column door_infos.sno
     *
     * @return the value of door_infos.sno
     * @mbg.generated
     */
    public String getSno() {
        return sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column door_infos.sno
     *
     * @param sno the value for door_infos.sno
     * @mbg.generated
     */
    public void setSno(String sno) {
        this.sno = sno == null ? null : sno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column door_infos.door_name
     *
     * @return the value of door_infos.door_name
     * @mbg.generated
     */
    public String getDoorName() {
        return doorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column door_infos.door_name
     *
     * @param doorName the value for door_infos.door_name
     * @mbg.generated
     */
    public void setDoorName(String doorName) {
        this.doorName = doorName == null ? null : doorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column door_infos.building_code
     *
     * @return the value of door_infos.building_code
     * @mbg.generated
     */
    public String getBuildingCode() {
        return buildingCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column door_infos.building_code
     *
     * @param buildingCode the value for door_infos.building_code
     * @mbg.generated
     */
    public void setBuildingCode(String buildingCode) {
        this.buildingCode = buildingCode == null ? null : buildingCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column door_infos.door_type
     *
     * @return the value of door_infos.door_type
     * @mbg.generated
     */
    public Integer getDoorType() {
        return doorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column door_infos.door_type
     *
     * @param doorType the value for door_infos.door_type
     * @mbg.generated
     */
    public void setDoorType(Integer doorType) {
        this.doorType = doorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column door_infos.door_building
     *
     * @return the value of door_infos.door_building
     * @mbg.generated
     */
    public String getDoorBuilding() {
        return doorBuilding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column door_infos.door_building
     *
     * @param doorBuilding the value for door_infos.door_building
     * @mbg.generated
     */
    public void setDoorBuilding(String doorBuilding) {
        this.doorBuilding = doorBuilding == null ? null : doorBuilding.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column door_infos.created_at
     *
     * @return the value of door_infos.created_at
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column door_infos.created_at
     *
     * @param createdAt the value for door_infos.created_at
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column door_infos.door_code
     *
     * @return the value of door_infos.door_code
     * @mbg.generated
     */
    public String getDoorCode() {
        return doorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column door_infos.door_code
     *
     * @param doorCode the value for door_infos.door_code
     * @mbg.generated
     */
    public void setDoorCode(String doorCode) {
        this.doorCode = doorCode == null ? null : doorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table door_infos
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", sno=").append(sno);
        sb.append(", doorName=").append(doorName);
        sb.append(", buildingCode=").append(buildingCode);
        sb.append(", doorType=").append(doorType);
        sb.append(", doorBuilding=").append(doorBuilding);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", doorCode=").append(doorCode);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}