package com.ykt.backstage.entity;

import java.io.Serializable;
import java.util.Date;

public class DormitoryWarning implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory_warning.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory_warning.xh
     *
     * @mbg.generated
     */
    private String xm;
    private String xh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory_warning.xb
     *
     * @mbg.generated
     */
    private String xb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory_warning.rxnj
     *
     * @mbg.generated
     */
    private String rxnj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory_warning.bjdm
     *
     * @mbg.generated
     */
    private String bjdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory_warning.zydm
     *
     * @mbg.generated
     */
    private String zydm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory_warning.ssfjh
     *
     * @mbg.generated
     */
    private String ssfjh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory_warning.jzwh
     *
     * @mbg.generated
     */
    private String jzwh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory_warning.warning_time
     *
     * @mbg.generated
     */
    private Date warningTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory_warning.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory_warning.update_at
     *
     * @mbg.generated
     */
    private Date updateAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory_warning.xjzt
     *
     * @mbg.generated
     */
    private String xjzt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory_warning.yxdm
     *
     * @mbg.generated
     */
    private String yxdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory_warning.xz
     *
     * @mbg.generated
     */
    private String xz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory_warning.zhcxsj
     *
     * @mbg.generated
     */
    private Date zhcxsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dormitory_warning
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory_warning.id
     *
     * @return the value of dormitory_warning.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory_warning.id
     *
     * @param id the value for dormitory_warning.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    public String getXm() {
        return xm;
    }

    public void setXm(String xm) {
        this.xm = xm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory_warning.xh
     *
     * @return the value of dormitory_warning.xh
     * @mbg.generated
     */


    public String getXh() {
        return xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory_warning.xh
     *
     * @param xh the value for dormitory_warning.xh
     * @mbg.generated
     */
    public void setXh(String xh) {
        this.xh = xh == null ? null : xh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory_warning.xb
     *
     * @return the value of dormitory_warning.xb
     * @mbg.generated
     */
    public String getXb() {
        return xb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory_warning.xb
     *
     * @param xb the value for dormitory_warning.xb
     * @mbg.generated
     */
    public void setXb(String xb) {
        this.xb = xb == null ? null : xb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory_warning.rxnj
     *
     * @return the value of dormitory_warning.rxnj
     * @mbg.generated
     */
    public String getRxnj() {
        return rxnj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory_warning.rxnj
     *
     * @param rxnj the value for dormitory_warning.rxnj
     * @mbg.generated
     */
    public void setRxnj(String rxnj) {
        this.rxnj = rxnj == null ? null : rxnj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory_warning.bjdm
     *
     * @return the value of dormitory_warning.bjdm
     * @mbg.generated
     */
    public String getBjdm() {
        return bjdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory_warning.bjdm
     *
     * @param bjdm the value for dormitory_warning.bjdm
     * @mbg.generated
     */
    public void setBjdm(String bjdm) {
        this.bjdm = bjdm == null ? null : bjdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory_warning.zydm
     *
     * @return the value of dormitory_warning.zydm
     * @mbg.generated
     */
    public String getZydm() {
        return zydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory_warning.zydm
     *
     * @param zydm the value for dormitory_warning.zydm
     * @mbg.generated
     */
    public void setZydm(String zydm) {
        this.zydm = zydm == null ? null : zydm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory_warning.ssfjh
     *
     * @return the value of dormitory_warning.ssfjh
     * @mbg.generated
     */
    public String getSsfjh() {
        return ssfjh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory_warning.ssfjh
     *
     * @param ssfjh the value for dormitory_warning.ssfjh
     * @mbg.generated
     */
    public void setSsfjh(String ssfjh) {
        this.ssfjh = ssfjh == null ? null : ssfjh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory_warning.jzwh
     *
     * @return the value of dormitory_warning.jzwh
     * @mbg.generated
     */
    public String getJzwh() {
        return jzwh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory_warning.jzwh
     *
     * @param jzwh the value for dormitory_warning.jzwh
     * @mbg.generated
     */
    public void setJzwh(String jzwh) {
        this.jzwh = jzwh == null ? null : jzwh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory_warning.warning_time
     *
     * @return the value of dormitory_warning.warning_time
     * @mbg.generated
     */
    public Date getWarningTime() {
        return warningTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory_warning.warning_time
     *
     * @param warningTime the value for dormitory_warning.warning_time
     * @mbg.generated
     */
    public void setWarningTime(Date warningTime) {
        this.warningTime = warningTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory_warning.created_at
     *
     * @return the value of dormitory_warning.created_at
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory_warning.created_at
     *
     * @param createdAt the value for dormitory_warning.created_at
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory_warning.update_at
     *
     * @return the value of dormitory_warning.update_at
     * @mbg.generated
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory_warning.update_at
     *
     * @param updateAt the value for dormitory_warning.update_at
     * @mbg.generated
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory_warning.xjzt
     *
     * @return the value of dormitory_warning.xjzt
     * @mbg.generated
     */
    public String getXjzt() {
        return xjzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory_warning.xjzt
     *
     * @param xjzt the value for dormitory_warning.xjzt
     * @mbg.generated
     */
    public void setXjzt(String xjzt) {
        this.xjzt = xjzt == null ? null : xjzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory_warning.yxdm
     *
     * @return the value of dormitory_warning.yxdm
     * @mbg.generated
     */
    public String getYxdm() {
        return yxdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory_warning.yxdm
     *
     * @param yxdm the value for dormitory_warning.yxdm
     * @mbg.generated
     */
    public void setYxdm(String yxdm) {
        this.yxdm = yxdm == null ? null : yxdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory_warning.xz
     *
     * @return the value of dormitory_warning.xz
     * @mbg.generated
     */
    public String getXz() {
        return xz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory_warning.xz
     *
     * @param xz the value for dormitory_warning.xz
     * @mbg.generated
     */
    public void setXz(String xz) {
        this.xz = xz == null ? null : xz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory_warning.zhcxsj
     *
     * @return the value of dormitory_warning.zhcxsj
     * @mbg.generated
     */
    public Date getZhcxsj() {
        return zhcxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory_warning.zhcxsj
     *
     * @param zhcxsj the value for dormitory_warning.zhcxsj
     * @mbg.generated
     */
    public void setZhcxsj(Date zhcxsj) {
        this.zhcxsj = zhcxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory_warning
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", xm=").append(xm);
        sb.append(", xh=").append(xh);
        sb.append(", xb=").append(xb);
        sb.append(", rxnj=").append(rxnj);
        sb.append(", bjdm=").append(bjdm);
        sb.append(", zydm=").append(zydm);
        sb.append(", ssfjh=").append(ssfjh);
        sb.append(", jzwh=").append(jzwh);
        sb.append(", warningTime=").append(warningTime);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", updateAt=").append(updateAt);
        sb.append(", xjzt=").append(xjzt);
        sb.append(", yxdm=").append(yxdm);
        sb.append(", xz=").append(xz);
        sb.append(", zhcxsj=").append(zhcxsj);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}