package com.ykt.backstage.entity;

import java.io.Serializable;
import java.util.Date;

public class Dormitory implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory.xh
     *
     * @mbg.generated
     */
    private String xh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory.xm
     *
     * @mbg.generated
     */
    private String xm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory.xqh
     *
     * @mbg.generated
     */
    private String xqh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory.jzwh
     *
     * @mbg.generated
     */
    private String jzwh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory.ssfjh
     *
     * @mbg.generated
     */
    private String ssfjh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory.cwh
     *
     * @mbg.generated
     */
    private String cwh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory.ssdh
     *
     * @mbg.generated
     */
    private String ssdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory.rzrq
     *
     * @mbg.generated
     */
    private Date rzrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory.qcrq
     *
     * @mbg.generated
     */
    private Date qcrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory.xwzz
     *
     * @mbg.generated
     */
    private String xwzz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dormitory.zcdh
     *
     * @mbg.generated
     */
    private String zcdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dormitory
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory.xh
     *
     * @return the value of dormitory.xh
     * @mbg.generated
     */
    public String getXh() {
        return xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory.xh
     *
     * @param xh the value for dormitory.xh
     * @mbg.generated
     */
    public void setXh(String xh) {
        this.xh = xh == null ? null : xh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory.xm
     *
     * @return the value of dormitory.xm
     * @mbg.generated
     */
    public String getXm() {
        return xm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory.xm
     *
     * @param xm the value for dormitory.xm
     * @mbg.generated
     */
    public void setXm(String xm) {
        this.xm = xm == null ? null : xm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory.xqh
     *
     * @return the value of dormitory.xqh
     * @mbg.generated
     */
    public String getXqh() {
        return xqh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory.xqh
     *
     * @param xqh the value for dormitory.xqh
     * @mbg.generated
     */
    public void setXqh(String xqh) {
        this.xqh = xqh == null ? null : xqh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory.jzwh
     *
     * @return the value of dormitory.jzwh
     * @mbg.generated
     */
    public String getJzwh() {
        return jzwh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory.jzwh
     *
     * @param jzwh the value for dormitory.jzwh
     * @mbg.generated
     */
    public void setJzwh(String jzwh) {
        this.jzwh = jzwh == null ? null : jzwh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory.ssfjh
     *
     * @return the value of dormitory.ssfjh
     * @mbg.generated
     */
    public String getSsfjh() {
        return ssfjh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory.ssfjh
     *
     * @param ssfjh the value for dormitory.ssfjh
     * @mbg.generated
     */
    public void setSsfjh(String ssfjh) {
        this.ssfjh = ssfjh == null ? null : ssfjh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory.cwh
     *
     * @return the value of dormitory.cwh
     * @mbg.generated
     */
    public String getCwh() {
        return cwh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory.cwh
     *
     * @param cwh the value for dormitory.cwh
     * @mbg.generated
     */
    public void setCwh(String cwh) {
        this.cwh = cwh == null ? null : cwh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory.ssdh
     *
     * @return the value of dormitory.ssdh
     * @mbg.generated
     */
    public String getSsdh() {
        return ssdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory.ssdh
     *
     * @param ssdh the value for dormitory.ssdh
     * @mbg.generated
     */
    public void setSsdh(String ssdh) {
        this.ssdh = ssdh == null ? null : ssdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory.rzrq
     *
     * @return the value of dormitory.rzrq
     * @mbg.generated
     */
    public Date getRzrq() {
        return rzrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory.rzrq
     *
     * @param rzrq the value for dormitory.rzrq
     * @mbg.generated
     */
    public void setRzrq(Date rzrq) {
        this.rzrq = rzrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory.qcrq
     *
     * @return the value of dormitory.qcrq
     * @mbg.generated
     */
    public Date getQcrq() {
        return qcrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory.qcrq
     *
     * @param qcrq the value for dormitory.qcrq
     * @mbg.generated
     */
    public void setQcrq(Date qcrq) {
        this.qcrq = qcrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory.xwzz
     *
     * @return the value of dormitory.xwzz
     * @mbg.generated
     */
    public String getXwzz() {
        return xwzz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory.xwzz
     *
     * @param xwzz the value for dormitory.xwzz
     * @mbg.generated
     */
    public void setXwzz(String xwzz) {
        this.xwzz = xwzz == null ? null : xwzz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dormitory.zcdh
     *
     * @return the value of dormitory.zcdh
     * @mbg.generated
     */
    public String getZcdh() {
        return zcdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dormitory.zcdh
     *
     * @param zcdh the value for dormitory.zcdh
     * @mbg.generated
     */
    public void setZcdh(String zcdh) {
        this.zcdh = zcdh == null ? null : zcdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dormitory
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", xh=").append(xh);
        sb.append(", xm=").append(xm);
        sb.append(", xqh=").append(xqh);
        sb.append(", jzwh=").append(jzwh);
        sb.append(", ssfjh=").append(ssfjh);
        sb.append(", cwh=").append(cwh);
        sb.append(", ssdh=").append(ssdh);
        sb.append(", rzrq=").append(rzrq);
        sb.append(", qcrq=").append(qcrq);
        sb.append(", xwzz=").append(xwzz);
        sb.append(", zcdh=").append(zcdh);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}