package com.ykt.backstage.entity;

import java.io.Serializable;
import java.util.Date;

public class FeedbackRecords implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback_records.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback_records.attendance_warnings_id
     *
     * @mbg.generated
     */
    private Integer attendanceWarningsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback_records.feedback_time
     *
     * @mbg.generated
     */
    private Date feedbackTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback_records.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback_records.created_user_id
     *
     * @mbg.generated
     */
    private String createdUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback_records.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback_records.description
     *
     * @mbg.generated
     */
    private String description;

    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table feedback_records
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;


    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback_records.id
     *
     * @return the value of feedback_records.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback_records.id
     *
     * @param id the value for feedback_records.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback_records.attendance_warnings_id
     *
     * @return the value of feedback_records.attendance_warnings_id
     * @mbg.generated
     */
    public Integer getAttendanceWarningsId() {
        return attendanceWarningsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback_records.attendance_warnings_id
     *
     * @param attendanceWarningsId the value for feedback_records.attendance_warnings_id
     * @mbg.generated
     */
    public void setAttendanceWarningsId(Integer attendanceWarningsId) {
        this.attendanceWarningsId = attendanceWarningsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback_records.feedback_time
     *
     * @return the value of feedback_records.feedback_time
     * @mbg.generated
     */
    public Date getFeedbackTime() {
        return feedbackTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback_records.feedback_time
     *
     * @param feedbackTime the value for feedback_records.feedback_time
     * @mbg.generated
     */
    public void setFeedbackTime(Date feedbackTime) {
        this.feedbackTime = feedbackTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback_records.created_by
     *
     * @return the value of feedback_records.created_by
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback_records.created_by
     *
     * @param createdBy the value for feedback_records.created_by
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback_records.created_user_id
     *
     * @return the value of feedback_records.created_user_id
     * @mbg.generated
     */
    public String getCreatedUserId() {
        return createdUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback_records.created_user_id
     *
     * @param createdUserId the value for feedback_records.created_user_id
     * @mbg.generated
     */
    public void setCreatedUserId(String createdUserId) {
        this.createdUserId = createdUserId == null ? null : createdUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback_records.created_at
     *
     * @return the value of feedback_records.created_at
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback_records.created_at
     *
     * @param createdAt the value for feedback_records.created_at
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback_records.description
     *
     * @return the value of feedback_records.description
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback_records.description
     *
     * @param description the value for feedback_records.description
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback_records
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", attendanceWarningsId=").append(attendanceWarningsId);
        sb.append(", feedbackTime=").append(feedbackTime);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", createdUserId=").append(createdUserId);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", description=").append(description);
        sb.append(", type=").append(type);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}