package com.ykt.backstage.entity;

import java.io.Serializable;

public class Grade implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.stuNum
     *
     * @mbg.generated
     */
    private String stunum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.yearSemester
     *
     * @mbg.generated
     */
    private String yearsemester;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.classNum
     *
     * @mbg.generated
     */
    private String classnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.className
     *
     * @mbg.generated
     */
    private String classname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.classType
     *
     * @mbg.generated
     */
    private Integer classtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.credit
     *
     * @mbg.generated
     */
    private String credit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.usualGrade
     *
     * @mbg.generated
     */
    private String usualgrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.examGrade
     *
     * @mbg.generated
     */
    private String examgrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.overallRating
     *
     * @mbg.generated
     */
    private String overallrating;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.finalGrade
     *
     * @mbg.generated
     */
    private String finalgrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.gradePoint
     *
     * @mbg.generated
     */
    private String gradepoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table grade
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.id
     *
     * @return the value of grade.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.id
     *
     * @param id the value for grade.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.stuNum
     *
     * @return the value of grade.stuNum
     * @mbg.generated
     */
    public String getStunum() {
        return stunum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.stuNum
     *
     * @param stunum the value for grade.stuNum
     * @mbg.generated
     */
    public void setStunum(String stunum) {
        this.stunum = stunum == null ? null : stunum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.yearSemester
     *
     * @return the value of grade.yearSemester
     * @mbg.generated
     */
    public String getYearsemester() {
        return yearsemester;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.yearSemester
     *
     * @param yearsemester the value for grade.yearSemester
     * @mbg.generated
     */
    public void setYearsemester(String yearsemester) {
        this.yearsemester = yearsemester == null ? null : yearsemester.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.classNum
     *
     * @return the value of grade.classNum
     * @mbg.generated
     */
    public String getClassnum() {
        return classnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.classNum
     *
     * @param classnum the value for grade.classNum
     * @mbg.generated
     */
    public void setClassnum(String classnum) {
        this.classnum = classnum == null ? null : classnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.className
     *
     * @return the value of grade.className
     * @mbg.generated
     */
    public String getClassname() {
        return classname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.className
     *
     * @param classname the value for grade.className
     * @mbg.generated
     */
    public void setClassname(String classname) {
        this.classname = classname == null ? null : classname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.classType
     *
     * @return the value of grade.classType
     * @mbg.generated
     */
    public Integer getClasstype() {
        return classtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.classType
     *
     * @param classtype the value for grade.classType
     * @mbg.generated
     */
    public void setClasstype(Integer classtype) {
        this.classtype = classtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.credit
     *
     * @return the value of grade.credit
     * @mbg.generated
     */
    public String getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.credit
     *
     * @param credit the value for grade.credit
     * @mbg.generated
     */
    public void setCredit(String credit) {
        this.credit = credit == null ? null : credit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.usualGrade
     *
     * @return the value of grade.usualGrade
     * @mbg.generated
     */
    public String getUsualgrade() {
        return usualgrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.usualGrade
     *
     * @param usualgrade the value for grade.usualGrade
     * @mbg.generated
     */
    public void setUsualgrade(String usualgrade) {
        this.usualgrade = usualgrade == null ? null : usualgrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.examGrade
     *
     * @return the value of grade.examGrade
     * @mbg.generated
     */
    public String getExamgrade() {
        return examgrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.examGrade
     *
     * @param examgrade the value for grade.examGrade
     * @mbg.generated
     */
    public void setExamgrade(String examgrade) {
        this.examgrade = examgrade == null ? null : examgrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.overallRating
     *
     * @return the value of grade.overallRating
     * @mbg.generated
     */
    public String getOverallrating() {
        return overallrating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.overallRating
     *
     * @param overallrating the value for grade.overallRating
     * @mbg.generated
     */
    public void setOverallrating(String overallrating) {
        this.overallrating = overallrating == null ? null : overallrating.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.finalGrade
     *
     * @return the value of grade.finalGrade
     * @mbg.generated
     */
    public String getFinalgrade() {
        return finalgrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.finalGrade
     *
     * @param finalgrade the value for grade.finalGrade
     * @mbg.generated
     */
    public void setFinalgrade(String finalgrade) {
        this.finalgrade = finalgrade == null ? null : finalgrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.gradePoint
     *
     * @return the value of grade.gradePoint
     * @mbg.generated
     */
    public String getGradepoint() {
        return gradepoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.gradePoint
     *
     * @param gradepoint the value for grade.gradePoint
     * @mbg.generated
     */
    public void setGradepoint(String gradepoint) {
        this.gradepoint = gradepoint == null ? null : gradepoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", stunum=").append(stunum);
        sb.append(", yearsemester=").append(yearsemester);
        sb.append(", classnum=").append(classnum);
        sb.append(", classname=").append(classname);
        sb.append(", classtype=").append(classtype);
        sb.append(", credit=").append(credit);
        sb.append(", usualgrade=").append(usualgrade);
        sb.append(", examgrade=").append(examgrade);
        sb.append(", overallrating=").append(overallrating);
        sb.append(", finalgrade=").append(finalgrade);
        sb.append(", gradepoint=").append(gradepoint);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}