package com.ykt.backstage.entity;

import java.io.Serializable;
import java.util.Date;

public class GradeWarning implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_warning.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_warning.sno
     *
     * @mbg.generated
     */
    private String sno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_warning.sname
     *
     * @mbg.generated
     */
    private String sname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_warning.class_code
     *
     * @mbg.generated
     */
    private String classCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_warning.major_code
     *
     * @mbg.generated
     */
    private String majorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_warning.department_code
     *
     * @mbg.generated
     */
    private String departmentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_warning.grade
     *
     * @mbg.generated
     */
    private String grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_warning.course_name
     *
     * @mbg.generated
     */
    private String courseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_warning.course_code
     *
     * @mbg.generated
     */
    private String courseCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_warning.course_grade
     *
     * @mbg.generated
     */
    private String courseGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_warning.wno
     *
     * @mbg.generated
     */
    private String wno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_warning.wname
     *
     * @mbg.generated
     */
    private String wname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_warning.w_department_code
     *
     * @mbg.generated
     */
    private String wDepartmentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_warning.created
     *
     * @mbg.generated
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_warning.updated
     *
     * @mbg.generated
     */
    private Date updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_warning.school_year
     *
     * @mbg.generated
     */
    private String schoolYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_warning.school_term
     *
     * @mbg.generated
     */
    private String schoolTerm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table grade_warning
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade_warning.id
     *
     * @return the value of grade_warning.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade_warning.id
     *
     * @param id the value for grade_warning.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade_warning.sno
     *
     * @return the value of grade_warning.sno
     * @mbg.generated
     */
    public String getSno() {
        return sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade_warning.sno
     *
     * @param sno the value for grade_warning.sno
     * @mbg.generated
     */
    public void setSno(String sno) {
        this.sno = sno == null ? null : sno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade_warning.sname
     *
     * @return the value of grade_warning.sname
     * @mbg.generated
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade_warning.sname
     *
     * @param sname the value for grade_warning.sname
     * @mbg.generated
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade_warning.class_code
     *
     * @return the value of grade_warning.class_code
     * @mbg.generated
     */
    public String getClassCode() {
        return classCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade_warning.class_code
     *
     * @param classCode the value for grade_warning.class_code
     * @mbg.generated
     */
    public void setClassCode(String classCode) {
        this.classCode = classCode == null ? null : classCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade_warning.major_code
     *
     * @return the value of grade_warning.major_code
     * @mbg.generated
     */
    public String getMajorCode() {
        return majorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade_warning.major_code
     *
     * @param majorCode the value for grade_warning.major_code
     * @mbg.generated
     */
    public void setMajorCode(String majorCode) {
        this.majorCode = majorCode == null ? null : majorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade_warning.department_code
     *
     * @return the value of grade_warning.department_code
     * @mbg.generated
     */
    public String getDepartmentCode() {
        return departmentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade_warning.department_code
     *
     * @param departmentCode the value for grade_warning.department_code
     * @mbg.generated
     */
    public void setDepartmentCode(String departmentCode) {
        this.departmentCode = departmentCode == null ? null : departmentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade_warning.grade
     *
     * @return the value of grade_warning.grade
     * @mbg.generated
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade_warning.grade
     *
     * @param grade the value for grade_warning.grade
     * @mbg.generated
     */
    public void setGrade(String grade) {
        this.grade = grade == null ? null : grade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade_warning.course_name
     *
     * @return the value of grade_warning.course_name
     * @mbg.generated
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade_warning.course_name
     *
     * @param courseName the value for grade_warning.course_name
     * @mbg.generated
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade_warning.course_code
     *
     * @return the value of grade_warning.course_code
     * @mbg.generated
     */
    public String getCourseCode() {
        return courseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade_warning.course_code
     *
     * @param courseCode the value for grade_warning.course_code
     * @mbg.generated
     */
    public void setCourseCode(String courseCode) {
        this.courseCode = courseCode == null ? null : courseCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade_warning.course_grade
     *
     * @return the value of grade_warning.course_grade
     * @mbg.generated
     */
    public String getCourseGrade() {
        return courseGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade_warning.course_grade
     *
     * @param courseGrade the value for grade_warning.course_grade
     * @mbg.generated
     */
    public void setCourseGrade(String courseGrade) {
        this.courseGrade = courseGrade == null ? null : courseGrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade_warning.wno
     *
     * @return the value of grade_warning.wno
     * @mbg.generated
     */
    public String getWno() {
        return wno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade_warning.wno
     *
     * @param wno the value for grade_warning.wno
     * @mbg.generated
     */
    public void setWno(String wno) {
        this.wno = wno == null ? null : wno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade_warning.wname
     *
     * @return the value of grade_warning.wname
     * @mbg.generated
     */
    public String getWname() {
        return wname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade_warning.wname
     *
     * @param wname the value for grade_warning.wname
     * @mbg.generated
     */
    public void setWname(String wname) {
        this.wname = wname == null ? null : wname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade_warning.w_department_code
     *
     * @return the value of grade_warning.w_department_code
     * @mbg.generated
     */
    public String getwDepartmentCode() {
        return wDepartmentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade_warning.w_department_code
     *
     * @param wDepartmentCode the value for grade_warning.w_department_code
     * @mbg.generated
     */
    public void setwDepartmentCode(String wDepartmentCode) {
        this.wDepartmentCode = wDepartmentCode == null ? null : wDepartmentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade_warning.created
     *
     * @return the value of grade_warning.created
     * @mbg.generated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade_warning.created
     *
     * @param created the value for grade_warning.created
     * @mbg.generated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade_warning.updated
     *
     * @return the value of grade_warning.updated
     * @mbg.generated
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade_warning.updated
     *
     * @param updated the value for grade_warning.updated
     * @mbg.generated
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade_warning.school_year
     *
     * @return the value of grade_warning.school_year
     * @mbg.generated
     */
    public String getSchoolYear() {
        return schoolYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade_warning.school_year
     *
     * @param schoolYear the value for grade_warning.school_year
     * @mbg.generated
     */
    public void setSchoolYear(String schoolYear) {
        this.schoolYear = schoolYear == null ? null : schoolYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade_warning.school_term
     *
     * @return the value of grade_warning.school_term
     * @mbg.generated
     */
    public String getSchoolTerm() {
        return schoolTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade_warning.school_term
     *
     * @param schoolTerm the value for grade_warning.school_term
     * @mbg.generated
     */
    public void setSchoolTerm(String schoolTerm) {
        this.schoolTerm = schoolTerm == null ? null : schoolTerm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade_warning
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", sno=").append(sno);
        sb.append(", sname=").append(sname);
        sb.append(", classCode=").append(classCode);
        sb.append(", majorCode=").append(majorCode);
        sb.append(", departmentCode=").append(departmentCode);
        sb.append(", grade=").append(grade);
        sb.append(", courseName=").append(courseName);
        sb.append(", courseCode=").append(courseCode);
        sb.append(", courseGrade=").append(courseGrade);
        sb.append(", wno=").append(wno);
        sb.append(", wname=").append(wname);
        sb.append(", wDepartmentCode=").append(wDepartmentCode);
        sb.append(", created=").append(created);
        sb.append(", updated=").append(updated);
        sb.append(", schoolYear=").append(schoolYear);
        sb.append(", schoolTerm=").append(schoolTerm);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}