package com.ykt.backstage.entity;

import java.io.Serializable;

public class LostWarningRule implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lost_warning_rule.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lost_warning_rule.warning_day
     *
     * @mbg.generated
     */
    private String warningDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lost_warning_rule.warning_day_start
     *
     * @mbg.generated
     */
    private String warningDayStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lost_warning_rule
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lost_warning_rule.id
     *
     * @return the value of lost_warning_rule.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lost_warning_rule.id
     *
     * @param id the value for lost_warning_rule.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lost_warning_rule.warning_day
     *
     * @return the value of lost_warning_rule.warning_day
     * @mbg.generated
     */
    public String getWarningDay() {
        return warningDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lost_warning_rule.warning_day
     *
     * @param warningDay the value for lost_warning_rule.warning_day
     * @mbg.generated
     */
    public void setWarningDay(String warningDay) {
        this.warningDay = warningDay == null ? null : warningDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lost_warning_rule.warning_day_start
     *
     * @return the value of lost_warning_rule.warning_day_start
     * @mbg.generated
     */
    public String getWarningDayStart() {
        return warningDayStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lost_warning_rule.warning_day_start
     *
     * @param warningDayStart the value for lost_warning_rule.warning_day_start
     * @mbg.generated
     */
    public void setWarningDayStart(String warningDayStart) {
        this.warningDayStart = warningDayStart == null ? null : warningDayStart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lost_warning_rule
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", warningDay=").append(warningDay);
        sb.append(", warningDayStart=").append(warningDayStart);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}