package com.ykt.backstage.entity;

import java.io.Serializable;

public class SchoolCalendarDetails implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_calendar_details.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_calendar_details.current_day
     *
     * @mbg.generated
     */
    private String currentDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_calendar_details.years
     *
     * @mbg.generated
     */
    private String years;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_calendar_details.months
     *
     * @mbg.generated
     */
    private String months;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_calendar_details.days
     *
     * @mbg.generated
     */
    private String days;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_calendar_details.current_week
     *
     * @mbg.generated
     */
    private String currentWeek;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_calendar_details.school_year
     *
     * @mbg.generated
     */
    private String schoolYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_calendar_details.school_term
     *
     * @mbg.generated
     */
    private String schoolTerm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_calendar_details.day_of_week
     *
     * @mbg.generated
     */
    private String dayOfWeek;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_calendar_details.comments
     *
     * @mbg.generated
     */
    private String comments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_calendar_details.created_at
     *
     * @mbg.generated
     */
    private String createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_calendar_details.updated_at
     *
     * @mbg.generated
     */
    private String updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_calendar_details.holiday_type
     *
     * @mbg.generated
     */
    private String holidayType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_calendar_details.vocation_type
     *
     * @mbg.generated
     */
    private String vocationType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table school_calendar_details
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_calendar_details.id
     *
     * @return the value of school_calendar_details.id
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_calendar_details.id
     *
     * @param id the value for school_calendar_details.id
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_calendar_details.current_day
     *
     * @return the value of school_calendar_details.current_day
     * @mbg.generated
     */
    public String getCurrentDay() {
        return currentDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_calendar_details.current_day
     *
     * @param currentDay the value for school_calendar_details.current_day
     * @mbg.generated
     */
    public void setCurrentDay(String currentDay) {
        this.currentDay = currentDay == null ? null : currentDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_calendar_details.years
     *
     * @return the value of school_calendar_details.years
     * @mbg.generated
     */
    public String getYears() {
        return years;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_calendar_details.years
     *
     * @param years the value for school_calendar_details.years
     * @mbg.generated
     */
    public void setYears(String years) {
        this.years = years == null ? null : years.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_calendar_details.months
     *
     * @return the value of school_calendar_details.months
     * @mbg.generated
     */
    public String getMonths() {
        return months;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_calendar_details.months
     *
     * @param months the value for school_calendar_details.months
     * @mbg.generated
     */
    public void setMonths(String months) {
        this.months = months == null ? null : months.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_calendar_details.days
     *
     * @return the value of school_calendar_details.days
     * @mbg.generated
     */
    public String getDays() {
        return days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_calendar_details.days
     *
     * @param days the value for school_calendar_details.days
     * @mbg.generated
     */
    public void setDays(String days) {
        this.days = days == null ? null : days.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_calendar_details.current_week
     *
     * @return the value of school_calendar_details.current_week
     * @mbg.generated
     */
    public String getCurrentWeek() {
        return currentWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_calendar_details.current_week
     *
     * @param currentWeek the value for school_calendar_details.current_week
     * @mbg.generated
     */
    public void setCurrentWeek(String currentWeek) {
        this.currentWeek = currentWeek == null ? null : currentWeek.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_calendar_details.school_year
     *
     * @return the value of school_calendar_details.school_year
     * @mbg.generated
     */
    public String getSchoolYear() {
        return schoolYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_calendar_details.school_year
     *
     * @param schoolYear the value for school_calendar_details.school_year
     * @mbg.generated
     */
    public void setSchoolYear(String schoolYear) {
        this.schoolYear = schoolYear == null ? null : schoolYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_calendar_details.school_term
     *
     * @return the value of school_calendar_details.school_term
     * @mbg.generated
     */
    public String getSchoolTerm() {
        return schoolTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_calendar_details.school_term
     *
     * @param schoolTerm the value for school_calendar_details.school_term
     * @mbg.generated
     */
    public void setSchoolTerm(String schoolTerm) {
        this.schoolTerm = schoolTerm == null ? null : schoolTerm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_calendar_details.day_of_week
     *
     * @return the value of school_calendar_details.day_of_week
     * @mbg.generated
     */
    public String getDayOfWeek() {
        return dayOfWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_calendar_details.day_of_week
     *
     * @param dayOfWeek the value for school_calendar_details.day_of_week
     * @mbg.generated
     */
    public void setDayOfWeek(String dayOfWeek) {
        this.dayOfWeek = dayOfWeek == null ? null : dayOfWeek.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_calendar_details.comments
     *
     * @return the value of school_calendar_details.comments
     * @mbg.generated
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_calendar_details.comments
     *
     * @param comments the value for school_calendar_details.comments
     * @mbg.generated
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_calendar_details.created_at
     *
     * @return the value of school_calendar_details.created_at
     * @mbg.generated
     */
    public String getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_calendar_details.created_at
     *
     * @param createdAt the value for school_calendar_details.created_at
     * @mbg.generated
     */
    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt == null ? null : createdAt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_calendar_details.updated_at
     *
     * @return the value of school_calendar_details.updated_at
     * @mbg.generated
     */
    public String getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_calendar_details.updated_at
     *
     * @param updatedAt the value for school_calendar_details.updated_at
     * @mbg.generated
     */
    public void setUpdatedAt(String updatedAt) {
        this.updatedAt = updatedAt == null ? null : updatedAt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_calendar_details.holiday_type
     *
     * @return the value of school_calendar_details.holiday_type
     * @mbg.generated
     */
    public String getHolidayType() {
        return holidayType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_calendar_details.holiday_type
     *
     * @param holidayType the value for school_calendar_details.holiday_type
     * @mbg.generated
     */
    public void setHolidayType(String holidayType) {
        this.holidayType = holidayType == null ? null : holidayType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_calendar_details.vocation_type
     *
     * @return the value of school_calendar_details.vocation_type
     * @mbg.generated
     */
    public String getVocationType() {
        return vocationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_calendar_details.vocation_type
     *
     * @param vocationType the value for school_calendar_details.vocation_type
     * @mbg.generated
     */
    public void setVocationType(String vocationType) {
        this.vocationType = vocationType == null ? null : vocationType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_calendar_details
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", currentDay=").append(currentDay);
        sb.append(", years=").append(years);
        sb.append(", months=").append(months);
        sb.append(", days=").append(days);
        sb.append(", currentWeek=").append(currentWeek);
        sb.append(", schoolYear=").append(schoolYear);
        sb.append(", schoolTerm=").append(schoolTerm);
        sb.append(", dayOfWeek=").append(dayOfWeek);
        sb.append(", comments=").append(comments);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append(", holidayType=").append(holidayType);
        sb.append(", vocationType=").append(vocationType);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}