package com.ykt.backstage.entity;

import java.io.Serializable;

public class Students implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.xh
     *
     * @mbg.generated
     */
    private String xh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.xm
     *
     * @mbg.generated
     */
    private String xm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.xslb
     *
     * @mbg.generated
     */
    private String xslb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.cym
     *
     * @mbg.generated
     */
    private String cym;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.ywxm
     *
     * @mbg.generated
     */
    private String ywxm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.xbm
     *
     * @mbg.generated
     */
    private Integer xbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.rxny
     *
     * @mbg.generated
     */
    private String rxny;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.rxnj
     *
     * @mbg.generated
     */
    private String rxnj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.csrq
     *
     * @mbg.generated
     */
    private String csrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.csdd
     *
     * @mbg.generated
     */
    private String csdd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.bjdm
     *
     * @mbg.generated
     */
    private String bjdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.sg
     *
     * @mbg.generated
     */
    private String sg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.tz
     *
     * @mbg.generated
     */
    private String tz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.zydm
     *
     * @mbg.generated
     */
    private String zydm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.yxdm
     *
     * @mbg.generated
     */
    private String yxdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.sfzx
     *
     * @mbg.generated
     */
    private Integer sfzx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.jg
     *
     * @mbg.generated
     */
    private String jg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.sfzlx
     *
     * @mbg.generated
     */
    private Integer sfzlx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.sfzjh
     *
     * @mbg.generated
     */
    private String sfzjh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.sfzyxq
     *
     * @mbg.generated
     */
    private String sfzyxq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.hyzk
     *
     * @mbg.generated
     */
    private String hyzk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.xyzj
     *
     * @mbg.generated
     */
    private String xyzj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.jkzk
     *
     * @mbg.generated
     */
    private String jkzk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.zzmm
     *
     * @mbg.generated
     */
    private String zzmm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.mz
     *
     * @mbg.generated
     */
    private String mz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.xx
     *
     * @mbg.generated
     */
    private String xx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.wx
     *
     * @mbg.generated
     */
    private String wx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.qq
     *
     * @mbg.generated
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.dh
     *
     * @mbg.generated
     */
    private String dh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.dszn
     *
     * @mbg.generated
     */
    private String dszn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.xjzt
     *
     * @mbg.generated
     */
    private Integer xjzt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table students
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.xh
     *
     * @return the value of students.xh
     * @mbg.generated
     */
    public String getXh() {
        return xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.xh
     *
     * @param xh the value for students.xh
     * @mbg.generated
     */
    public void setXh(String xh) {
        this.xh = xh == null ? null : xh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.xm
     *
     * @return the value of students.xm
     * @mbg.generated
     */
    public String getXm() {
        return xm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.xm
     *
     * @param xm the value for students.xm
     * @mbg.generated
     */
    public void setXm(String xm) {
        this.xm = xm == null ? null : xm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.xslb
     *
     * @return the value of students.xslb
     * @mbg.generated
     */
    public String getXslb() {
        return xslb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.xslb
     *
     * @param xslb the value for students.xslb
     * @mbg.generated
     */
    public void setXslb(String xslb) {
        this.xslb = xslb == null ? null : xslb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.cym
     *
     * @return the value of students.cym
     * @mbg.generated
     */
    public String getCym() {
        return cym;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.cym
     *
     * @param cym the value for students.cym
     * @mbg.generated
     */
    public void setCym(String cym) {
        this.cym = cym == null ? null : cym.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.ywxm
     *
     * @return the value of students.ywxm
     * @mbg.generated
     */
    public String getYwxm() {
        return ywxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.ywxm
     *
     * @param ywxm the value for students.ywxm
     * @mbg.generated
     */
    public void setYwxm(String ywxm) {
        this.ywxm = ywxm == null ? null : ywxm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.xbm
     *
     * @return the value of students.xbm
     * @mbg.generated
     */
    public Integer getXbm() {
        return xbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.xbm
     *
     * @param xbm the value for students.xbm
     * @mbg.generated
     */
    public void setXbm(Integer xbm) {
        this.xbm = xbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.rxny
     *
     * @return the value of students.rxny
     * @mbg.generated
     */
    public String getRxny() {
        return rxny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.rxny
     *
     * @param rxny the value for students.rxny
     * @mbg.generated
     */
    public void setRxny(String rxny) {
        this.rxny = rxny == null ? null : rxny.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.rxnj
     *
     * @return the value of students.rxnj
     * @mbg.generated
     */
    public String getRxnj() {
        return rxnj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.rxnj
     *
     * @param rxnj the value for students.rxnj
     * @mbg.generated
     */
    public void setRxnj(String rxnj) {
        this.rxnj = rxnj == null ? null : rxnj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.csrq
     *
     * @return the value of students.csrq
     * @mbg.generated
     */
    public String getCsrq() {
        return csrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.csrq
     *
     * @param csrq the value for students.csrq
     * @mbg.generated
     */
    public void setCsrq(String csrq) {
        this.csrq = csrq == null ? null : csrq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.csdd
     *
     * @return the value of students.csdd
     * @mbg.generated
     */
    public String getCsdd() {
        return csdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.csdd
     *
     * @param csdd the value for students.csdd
     * @mbg.generated
     */
    public void setCsdd(String csdd) {
        this.csdd = csdd == null ? null : csdd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.bjdm
     *
     * @return the value of students.bjdm
     * @mbg.generated
     */
    public String getBjdm() {
        return bjdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.bjdm
     *
     * @param bjdm the value for students.bjdm
     * @mbg.generated
     */
    public void setBjdm(String bjdm) {
        this.bjdm = bjdm == null ? null : bjdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.sg
     *
     * @return the value of students.sg
     * @mbg.generated
     */
    public String getSg() {
        return sg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.sg
     *
     * @param sg the value for students.sg
     * @mbg.generated
     */
    public void setSg(String sg) {
        this.sg = sg == null ? null : sg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.tz
     *
     * @return the value of students.tz
     * @mbg.generated
     */
    public String getTz() {
        return tz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.tz
     *
     * @param tz the value for students.tz
     * @mbg.generated
     */
    public void setTz(String tz) {
        this.tz = tz == null ? null : tz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.zydm
     *
     * @return the value of students.zydm
     * @mbg.generated
     */
    public String getZydm() {
        return zydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.zydm
     *
     * @param zydm the value for students.zydm
     * @mbg.generated
     */
    public void setZydm(String zydm) {
        this.zydm = zydm == null ? null : zydm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.yxdm
     *
     * @return the value of students.yxdm
     * @mbg.generated
     */
    public String getYxdm() {
        return yxdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.yxdm
     *
     * @param yxdm the value for students.yxdm
     * @mbg.generated
     */
    public void setYxdm(String yxdm) {
        this.yxdm = yxdm == null ? null : yxdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.sfzx
     *
     * @return the value of students.sfzx
     * @mbg.generated
     */
    public Integer getSfzx() {
        return sfzx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.sfzx
     *
     * @param sfzx the value for students.sfzx
     * @mbg.generated
     */
    public void setSfzx(Integer sfzx) {
        this.sfzx = sfzx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.jg
     *
     * @return the value of students.jg
     * @mbg.generated
     */
    public String getJg() {
        return jg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.jg
     *
     * @param jg the value for students.jg
     * @mbg.generated
     */
    public void setJg(String jg) {
        this.jg = jg == null ? null : jg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.sfzlx
     *
     * @return the value of students.sfzlx
     * @mbg.generated
     */
    public Integer getSfzlx() {
        return sfzlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.sfzlx
     *
     * @param sfzlx the value for students.sfzlx
     * @mbg.generated
     */
    public void setSfzlx(Integer sfzlx) {
        this.sfzlx = sfzlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.sfzjh
     *
     * @return the value of students.sfzjh
     * @mbg.generated
     */
    public String getSfzjh() {
        return sfzjh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.sfzjh
     *
     * @param sfzjh the value for students.sfzjh
     * @mbg.generated
     */
    public void setSfzjh(String sfzjh) {
        this.sfzjh = sfzjh == null ? null : sfzjh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.sfzyxq
     *
     * @return the value of students.sfzyxq
     * @mbg.generated
     */
    public String getSfzyxq() {
        return sfzyxq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.sfzyxq
     *
     * @param sfzyxq the value for students.sfzyxq
     * @mbg.generated
     */
    public void setSfzyxq(String sfzyxq) {
        this.sfzyxq = sfzyxq == null ? null : sfzyxq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.hyzk
     *
     * @return the value of students.hyzk
     * @mbg.generated
     */
    public String getHyzk() {
        return hyzk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.hyzk
     *
     * @param hyzk the value for students.hyzk
     * @mbg.generated
     */
    public void setHyzk(String hyzk) {
        this.hyzk = hyzk == null ? null : hyzk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.xyzj
     *
     * @return the value of students.xyzj
     * @mbg.generated
     */
    public String getXyzj() {
        return xyzj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.xyzj
     *
     * @param xyzj the value for students.xyzj
     * @mbg.generated
     */
    public void setXyzj(String xyzj) {
        this.xyzj = xyzj == null ? null : xyzj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.jkzk
     *
     * @return the value of students.jkzk
     * @mbg.generated
     */
    public String getJkzk() {
        return jkzk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.jkzk
     *
     * @param jkzk the value for students.jkzk
     * @mbg.generated
     */
    public void setJkzk(String jkzk) {
        this.jkzk = jkzk == null ? null : jkzk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.zzmm
     *
     * @return the value of students.zzmm
     * @mbg.generated
     */
    public String getZzmm() {
        return zzmm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.zzmm
     *
     * @param zzmm the value for students.zzmm
     * @mbg.generated
     */
    public void setZzmm(String zzmm) {
        this.zzmm = zzmm == null ? null : zzmm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.mz
     *
     * @return the value of students.mz
     * @mbg.generated
     */
    public String getMz() {
        return mz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.mz
     *
     * @param mz the value for students.mz
     * @mbg.generated
     */
    public void setMz(String mz) {
        this.mz = mz == null ? null : mz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.xx
     *
     * @return the value of students.xx
     * @mbg.generated
     */
    public String getXx() {
        return xx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.xx
     *
     * @param xx the value for students.xx
     * @mbg.generated
     */
    public void setXx(String xx) {
        this.xx = xx == null ? null : xx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.wx
     *
     * @return the value of students.wx
     * @mbg.generated
     */
    public String getWx() {
        return wx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.wx
     *
     * @param wx the value for students.wx
     * @mbg.generated
     */
    public void setWx(String wx) {
        this.wx = wx == null ? null : wx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.qq
     *
     * @return the value of students.qq
     * @mbg.generated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.qq
     *
     * @param qq the value for students.qq
     * @mbg.generated
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.dh
     *
     * @return the value of students.dh
     * @mbg.generated
     */
    public String getDh() {
        return dh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.dh
     *
     * @param dh the value for students.dh
     * @mbg.generated
     */
    public void setDh(String dh) {
        this.dh = dh == null ? null : dh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.dszn
     *
     * @return the value of students.dszn
     * @mbg.generated
     */
    public String getDszn() {
        return dszn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.dszn
     *
     * @param dszn the value for students.dszn
     * @mbg.generated
     */
    public void setDszn(String dszn) {
        this.dszn = dszn == null ? null : dszn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.xjzt
     *
     * @return the value of students.xjzt
     * @mbg.generated
     */
    public Integer getXjzt() {
        return xjzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.xjzt
     *
     * @param xjzt the value for students.xjzt
     * @mbg.generated
     */
    public void setXjzt(Integer xjzt) {
        this.xjzt = xjzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", xh=").append(xh);
        sb.append(", xm=").append(xm);
        sb.append(", xslb=").append(xslb);
        sb.append(", cym=").append(cym);
        sb.append(", ywxm=").append(ywxm);
        sb.append(", xbm=").append(xbm);
        sb.append(", rxny=").append(rxny);
        sb.append(", rxnj=").append(rxnj);
        sb.append(", csrq=").append(csrq);
        sb.append(", csdd=").append(csdd);
        sb.append(", bjdm=").append(bjdm);
        sb.append(", sg=").append(sg);
        sb.append(", tz=").append(tz);
        sb.append(", zydm=").append(zydm);
        sb.append(", yxdm=").append(yxdm);
        sb.append(", sfzx=").append(sfzx);
        sb.append(", jg=").append(jg);
        sb.append(", sfzlx=").append(sfzlx);
        sb.append(", sfzjh=").append(sfzjh);
        sb.append(", sfzyxq=").append(sfzyxq);
        sb.append(", hyzk=").append(hyzk);
        sb.append(", xyzj=").append(xyzj);
        sb.append(", jkzk=").append(jkzk);
        sb.append(", zzmm=").append(zzmm);
        sb.append(", mz=").append(mz);
        sb.append(", xx=").append(xx);
        sb.append(", wx=").append(wx);
        sb.append(", qq=").append(qq);
        sb.append(", dh=").append(dh);
        sb.append(", dszn=").append(dszn);
        sb.append(", xjzt=").append(xjzt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}