package com.ykt.backstage.entity;

import java.io.Serializable;
import java.util.Date;

public class TeacherClasses implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_classes.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_classes.wno
     *
     * @mbg.generated
     */
    private String wno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_classes.class_no
     *
     * @mbg.generated
     */
    private String classNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_classes.stu_class_id
     *
     * @mbg.generated
     */
    private Integer stuClassId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_classes.person_type
     *
     * @mbg.generated
     */
    private String personType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_classes.stu_type
     *
     * @mbg.generated
     */
    private Integer stuType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_classes.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_classes.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table teacher_classes
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_classes.id
     *
     * @return the value of teacher_classes.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_classes.id
     *
     * @param id the value for teacher_classes.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_classes.wno
     *
     * @return the value of teacher_classes.wno
     * @mbg.generated
     */
    public String getWno() {
        return wno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_classes.wno
     *
     * @param wno the value for teacher_classes.wno
     * @mbg.generated
     */
    public void setWno(String wno) {
        this.wno = wno == null ? null : wno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_classes.class_no
     *
     * @return the value of teacher_classes.class_no
     * @mbg.generated
     */
    public String getClassNo() {
        return classNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_classes.class_no
     *
     * @param classNo the value for teacher_classes.class_no
     * @mbg.generated
     */
    public void setClassNo(String classNo) {
        this.classNo = classNo == null ? null : classNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_classes.stu_class_id
     *
     * @return the value of teacher_classes.stu_class_id
     * @mbg.generated
     */
    public Integer getStuClassId() {
        return stuClassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_classes.stu_class_id
     *
     * @param stuClassId the value for teacher_classes.stu_class_id
     * @mbg.generated
     */
    public void setStuClassId(Integer stuClassId) {
        this.stuClassId = stuClassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_classes.person_type
     *
     * @return the value of teacher_classes.person_type
     * @mbg.generated
     */
    public String getPersonType() {
        return personType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_classes.person_type
     *
     * @param personType the value for teacher_classes.person_type
     * @mbg.generated
     */
    public void setPersonType(String personType) {
        this.personType = personType == null ? null : personType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_classes.stu_type
     *
     * @return the value of teacher_classes.stu_type
     * @mbg.generated
     */
    public Integer getStuType() {
        return stuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_classes.stu_type
     *
     * @param stuType the value for teacher_classes.stu_type
     * @mbg.generated
     */
    public void setStuType(Integer stuType) {
        this.stuType = stuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_classes.created_at
     *
     * @return the value of teacher_classes.created_at
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_classes.created_at
     *
     * @param createdAt the value for teacher_classes.created_at
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_classes.updated_at
     *
     * @return the value of teacher_classes.updated_at
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_classes.updated_at
     *
     * @param updatedAt the value for teacher_classes.updated_at
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_classes
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", wno=").append(wno);
        sb.append(", classNo=").append(classNo);
        sb.append(", stuClassId=").append(stuClassId);
        sb.append(", personType=").append(personType);
        sb.append(", stuType=").append(stuType);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}